### ISSUE TITLE
mediaserver example points to deprecated headers

### ISSUE THREAD

**Issue by MarceloEmmerich** [sourcey/libsourcey#108]
libsourcey built under windows 10. Then tried to build the av/mediaserver example, but the example points to deprecated headers, like #include "scy/av/mediafactory.h".

**Comment by auscaster** [comment]
This has been fixed.

**Comment by usmanghani** [comment]
I don't see the fix. In latest master its still pointing to deprecated headers

**Comment by auscaster** [comment]
It compiles fine for me. Can you please be more specific?

>

**Comment by usmanghani** [comment]
What I mean is media server fails to compile because it is still pointing to deprecated headers. getFrame doesn't exist in the new VideoCapture class but it is still part of the latest master snapshotresponder.h file.
https://github.com/sourcey/libsourcey/blob/master/src/av/samples/mediaserver/snapshotresponder.h#L26
