### ISSUE TITLE
parallel http requests example

### ISSUE THREAD

**Issue by WeissGotsman** [sourcey/libsourcey#112]
is there any code snippet in libsourcey that handles a large numebr of http requests (to different urls) efficiently? I suppose async is the expertise of libuv.

e.g. 64 threads that maintain 640 connections and doing 640000 requests

**Comment by auscaster** [comment]
The echo server example handles parallel HTTP requests - you can use it as
a base to work from. I don't have any benchmarks but its extremely fast,
just an oop layer over libuv and the http parser from nginx.

**Comment by WeissGotsman** [comment]
sorry, I mean make parallel http request from the client side. 

I checked the "standalone client connection" code in httptests, but if I simply wrap it with a for loop it does not seems to be efficient because:

every time it calls "void ClientConnection::send()" a new socket connection is established with dns resolution. 

I can wrap libuv to make it more efficient, but prefer an official API

I'm also interested to seem whether libuv can beat aeloop from redis as used in wrk

https://github.com/wg/wrk

**Comment by WeissGotsman** [comment]
OK, I did a simple test, even the http server of libsourcy is not fast

Requests/sec:   1673.68   libsourcey head version 
Requests/sec:  11805.36  apache httpd 2.4.23
Requests/sec:   35402.00  crow head version https://github.com/ipkn/crow/
Requests/sec:   32381.25 haywire head version https://github.com/haywire/haywire

**Comment by auscaster** [comment]
Thanks for the test results, when time permits I'll look a bit deeper and
maybe do some comparisons with a raw libuv implementation.

Regarding the multiple client requests DNS resolution issue, it could be
solved by overriding the HTTP client to call the `Socket::connect(const
Address& address)` with a raw IP address rather than `Socket::connect(const
std::string& host, std::uint16_t port);` with a hostname that will always
require DNS resolution.

**Comment by auscaster** [comment]
OK I just checked into the code - you can connect to a raw IP address with the current implementation to bypass DNS resolution.

**Comment by auscaster** [comment]
Closing as solved.
