### ISSUE TITLE
any advise  on the loadbalance of  turnserver?

### ISSUE THREAD

**Issue by notedit** [sourcey/libsourcey#113]

**Comment by auscaster** [comment]
HAProxy using a round robin load balancing would be ideal and not too challenging to setup. 

In production I would also look at extending the TURN server app to report stats to a central HTTP server.

**Comment by notedit** [comment]
i also  read this  https://github.com/coturn/coturn/issues/90

"
If you read the TURN specs, you will see that it was
designed in the way that make third-party load-balancing a very difficult
thing
"

i didn't dig two  much to  turn specs,    i  don't know whether turn server can support loadbalance or not

**Comment by auscaster** [comment]
Also check into the ALTERNATE-SERVER mechanism that lets the server specify
an alternate server to the client. This is useful if you want the TURN
server to redirect the client if its almost full.

**Comment by hilbix** [comment]
Note that I think that load-balancing/NATting TURNservers simply does not make any sense.
(This here is not about firewalling, as these are completely different beasts than LBs or NAT.)

The reason behind LB is:

- High availability
- Allow to distribute the load to multiple slow servers
- Some stupid network design which cannot be changed at all
- (d)DoS-Protection

The reason for NAT are:

- IP conservation:  Multiplex several disjunct services onto a single IP
- Poor man's firewall, if stateful like Masquerading
- Poor man's Load-Balancing (sic!)
- VM hosting
- Other reasons (like address translation for braindead applications, MitM attacks, etc.)

None of these reasons hold when it comes to TURNservers.  TURNservers usually mean to create extreme stress to the network, so if something needs DoS protection, it's the network with all of it's routers, and not the TURNserver.

- Raw network bandwidth is crucial to TURN servers.  Adding a single component of just 1ms delay creates 4ms more RTT!  (`A->1ms->TURN->1ms->B->1ms->TURN->1ms->A`)
- TURN servers have minimal processing requirements.  80% (or more?) of the load is just data shifting from one side to the other.
- NAT and unnecessary packet processings (like LBs) double or more the CPU time needed to process the requests.

# Placement of TURN server

Hence the only right thing you can do with a TURN server is to have it bare-metal plugged in directly behind your border router, nearest to from where the major traffic is expected.  Do not even consider to put it behind a firewall, just close down the machine as good as possible (for example a secondary administrative interface not reachable from Internet, which is NOT connected to the DMZ directly - there must be a firewall to protect the DMZ).

So your network might look like:

```
Internet <-> BorderRouter <-+-> Firewall <-> DMZ <- Firewall <- Intranet
                            !
                            +-> TURNserver
```

or:

```
Internet <-> ISP <-+-> VMhost <-+- VM1
                   !            +- VM2
                   !            +- ..
                   +-> TURNserver                 
```

If you only have a single machine, you can run the TURNserver directly on Host.  But I do not recommend to do so.

Putting it into a VM only is good for experimental low-bandwidth setups.  Do not do this on production.


# HA

If you need HA, then use a failover setting, with either the routers doing failover on MAC layer or there is some IP takeover between the two machines.  You can have the second TURNserver handle excess load.

This might be good for a single site setup, if you do not have any need to scale.

However I do not think HA really is needed, because you can implement the loadbalancing at client side right from the beginning (see next).  This allows you to dedicate 2 or more bare metal machines to TURNservers and distribute them between different ISPs, so if one of them goes down just nothing happens (except all clients must be shifted to the still running TURN server).


# LB

Don't even think about load balancing.  It adds several problems to a simple thing.  A dedicated load balancer does not help, at best it does not harm but it never will improve things.

The trouble with load balancing is, that 2 different clients must be connected to the same TURN server.  This needs to be communicated to the LB somehow.  Also be prepared for reconnects after network outages, so two clients might need to re-connect via TURN after hours, which adds the need to keep some nearly unnecessary state information.  Also be prepared for the hell breaking loose at a more or less regular basis.  Therefor all you need is a rock-solid setup.  If you fail on TURN, you will see unpredictable failures at a global scale, which are hard to debug.  Do not experiment, just do the right thing.

Just implement the loadbalancing at the client level.

You already have signalling, right?  You also use authentication, such that not everybody on this planet can use your bandwidth, right?  And, if you are big enough to use GeoLocation, you want to choose the right TURN server for the current seen clients, right?

So it should not be complex to just hand out your best TURN server, just for a case-by-case basis.

- If one TURNserver goes down unexpectedly, the clients detect that and request a new one.  Solved.
- If one TURNserver gets overloaded, just do not hand out this one to clients.  Solved.

If you are concerned about security, have a good monitoring and a throw-away setup for the bare metal machine.  It's easy and convenient.  TURN servers do not need to keep data around.  Logging is done with monitoring instead.  Solved, too.


# Final thoughts

If you want some easy to manage setup which is easy to maintain and cheap, up to several Gigabit/s, here is one idea (I haven't tested it so far, but I am confident that this is correct):

Use Raspberry PIs as TURN server devices.  No, really, that looks like a valid option.

Those devices are cheap and have enough power to max-out their 100 MBit/s interface.  (Note that similar devices like the Banana PI can only utilize around 330 MBit/s out out their GBit-Interface.  So perhaps add two USB Ethernet ports and you reach the same with the PI.  But I would recommend to just add more PIs instead.)

Scaling the network is easy this way:  Just add more PIs until your total maximum bandwidth is reached.  No need for difficult capping.  No difficult calculations.  No difficult setups.  If your PIs are maxed out you hit the roof.  Easy and convenient.  And easy to scale and spread over more than one location.

Hardware replacement is a breeze.  Just plug in a new PI with some preset SD-card which initializes itself for your setup the first time it is booted.  Done.

Some evil security-Flaw hits and you have been hacked?  Well, prepare a new image.  Write it onto SD cards and replace those on the PIs.  This is cheap and easy as well.  The only drawback is, you need a good pair of tweezers.

And over all the combined power consumption of the PIs is probably less than what your border gateway needs ..

HTH
