### ISSUE TITLE
Build issue webrtc openssl

### ISSUE THREAD

**Issue by AdoPi** [sourcey/libsourcey#134]
Hello!

I have some problems when I try to build libsourcey with webrtc.

I changed the variable WEBRTC_ROOT_DIR in the FindWebRTC.cmake file as below:
`set(WEBRTC_ROOT_DIR ${LibSourcey_DIR}/vendor/webrtc/out/src/ )`

I try to cmake with this command:
` cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DWITH_WEBRTC=ON -DBUILD_SHARED_LIBS=OFF`

And here the error which is produced :
`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
~/dev/test-build-sourcey/test2/libsourcey/src/archo/OPENSSL_INCLUDE_DIR
   used as include directory in directory ~/dev/test-build-sourcey/test2/libsourcey/src/archo
...`

Thanks for your help!

**Comment by AdoPi** [comment]
The WEBRTC_ROOT_DIR is unset in LibSourcey.cmake
So I have just added this line: set(WEBRTC_ROOT_DIR ${LibSourcey_DIR}/external/webrtc/out/src/ )
at the line 237.

Then I have commented the "find_package(OpenSSL) line 207.

Thanks to that, cmakes works :+1:

**Comment by dkushner** [comment]
I am also having this issue, despite specifying -DOPENSSL_INCLUDE_DIR in the CMake arguments. Is there no way to make this work without actually modifying the project's CMake files?

**Comment by auscaster** [comment]
By the way openssl is not used with webrtc. Boringssl is used instead.

On 30 Jul 2017 10:44 am, wrote:

Hi Dave

It should certainly work without needing to modify anything. What cmake
version, platform and command line are you using?

On 30 Jul 2017 1:32 am, "Dave Kushner" <notifications@github.com> wrote:

I am also having this issue, despite specifying -DOPENSSL_INCLUDE_DIR in
the CMake arguments. Is there no way to make this work without actually
modifying the project's CMake files?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sourcey/libsourcey/issues/134#issuecomment-318866510>,
or mute the thread

**Comment by auscaster** [comment]
Hi Dave

It should certainly work without needing to modify anything. What cmake
version, platform and command line are you using?

**Comment by dkushner** [comment]
Hey @auscaster, this issue cleared up when I just went and downloaded the pre-compiled binaries for WebRTC. I was trying to make this work by side-buidling libwebrtc as a dependency in CMake. It turns out that the directory structure it creates is slightly different from what LibSourcey suspects. The error was quite misleading though, as I was trying to address some issue with my OpenSSL installation when, in reality, this was caused by an unset WEBRTC_ROOT_DIR.

**Comment by auscaster** [comment]
Thanks for the response Dave - it would be good to handle this case in
libsourcey, would you be able to push a PR or maybe help me understand how
the directory structure differs so I can help support it?

**Comment by sxcsfan** [comment]
@dkushner you are right. It is caused by an unset WEBRTC_ROOT_DIR.
Download the pre built webrtc package and unarchive it, and add `-DWEBRTC_ROOT_DIR=path/to/pre-built/webrtc/library` and `-DWEBRTC_ROOT_DIR=path/to/pre-built/webrtc/library/include` to your cmake command and it will work.
