### ISSUE TITLE
Could NOT find FFmpeg (missing: FFmpeg_INCLUDE_DIRS) in Mint17

### ISSUE THREAD

**Issue by bevinhex** [sourcey/libsourcey#25]
When I trie to compile libsourcey in Linux Mint 17, here is my command
```shell
git clone https://github.com/sourcey/libsourcey
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=RELEASE
```
then I got following output:
```shell
-- Detected version of GNU GCC: 48 (408)
-- checking for one of the modules 'libswresample'
CMake Error at /usr/local/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find FFmpeg (missing: FFmpeg_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  cmake/LibSourceyIncludes.cmake:327 (find_package_handle_standard_args)
  cmake/FindFFmpeg.cmake:57 (set_module_found)
  cmake/LibSourceyIncludes.cmake:105 (find_package)
  CMakeLists.txt:325 (include_dependency)


-- Configuring incomplete, errors occurred!
See also "/home/bevin/Downloads/libsourcey/build/CMakeFiles/CMakeOutput.log".
```

**Comment by bevinhex** [comment]
I only wanted to test the library to know what exactly it is, but after frustrating with the compiling process, I already gave up, looks like we need ffmpeg souce code, and specify it by FFmpeg_INCLUDE_DIRS, I didn't tried it myself, you can give it a try.
And I hate to compile download the ffmpeg stuff, since it should be in the repository

**Comment by Oddwel** [comment]
Ended up using Qt instead. Much less effort into the getting of the tools. I agree with bevinhex, those "third parties" should be redistributed, or at least redirected to how to get them.

**Comment by auscaster** [comment]
I made an effort to include most dependencies in the source tree, with the exception of ffmpeg and openssl which aren't convenient for redistribution.

There are two options here...

Please either build ffmpeg on your system by following one of the [many guides out there](https://trac.ffmpeg.org/wiki/CompilationGuide). Once installed, CMake should configure ffmpeg automatically thanks to the pkgconfig files, otherwise just specify the FFmpeg_INCLUDE_DIRS and FFmpeg_LIBRARY_DIRS manually.

The other alternative is to disable ffmpeg support entirely by setting WITH_FFMPEG to OFF. This will also exclude many of the media related modules from the output build.

Hope this helps.
